# Generated by Django 4.2.19 on 2025-03-27 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftinfo',
            name='hero',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='draft_selections',
                to='api.hero',
                verbose_name='Hero'
            ),
        ),
        migrations.AlterField(
            model_name='playermatchstat',
            name='hero_played',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='match_stats',
                to='api.hero',
                verbose_name='Hero'
            ),
        ),
    ]
