# Generated by Django 4.2.19 on 2025-02-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="primary_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("JUNGLER", "Jungler"),
                    ("MID", "Mid Laner"),
                    ("ROAMER", "Roamer"),
                    ("EXP", "Exp Laner"),
                    ("GOLD", "Gold Laner"),
                    ("FLEX", "Flex Player"),
                    ("COACH", "Coach"),
                    ("ANALYST", "Analyst"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
