# Generated by Django 4.2.19 on 2025-02-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_player_primary_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrimgroup",
            name="end_date",
        ),
        migrations.AlterField(
            model_name="match",
            name="match_outcome",
            field=models.CharField(
                choices=[("VICTORY", "Victory"), ("DEFEAT", "Defeat")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="scrim_type",
            field=models.CharField(
                choices=[
                    ("SCRIMMAGE", "Scrimmage"),
                    ("TOURNAMENT", "Tournament"),
                    ("RANKED", "Ranked"),
                ],
                default="PRACTICE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team_side",
            field=models.CharField(
                choices=[("BLUE", "Blue Side"), ("RED", "Red Side")], max_length=10
            ),
        ),
    ]
