# Generated by Django 4.2.19 on 2025-03-27 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_populate_hero_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftinfo",
            name="hero",
            field=models.ForeignKey(
                db_column="hero_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="draft_selections",
                to="api.hero",
                verbose_name="Hero",
            ),
        ),
        migrations.AlterField(
            model_name="playermatchstat",
            name="hero_played",
            field=models.ForeignKey(
                db_column="hero_played_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="match_stats",
                to="api.hero",
                verbose_name="Hero",
            ),
        ),
    ]
