# Generated by Django 4.2.19 on 2025-02-27 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_remove_scrimgroup_end_date_alter_match_match_outcome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_opponent_only",
            field=models.BooleanField(
                default=False,
                help_text="Check this if this team is only used as an opponent and not managed by any users",
                verbose_name="Opponent Team Only",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="managers",
            field=models.ManyToManyField(
                blank=True, related_name="managed_teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
