# Generated by Django 4.2.19 on 2025-02-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_team_is_opponent_only_alter_team_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_duration",
            field=models.DurationField(
                blank=True, help_text="Duration of the match (HH:MM:SS)", null=True
            ),
        ),
    ]
