# Generated by Django 4.2.19 on 2025-02-27 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_match_match_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="match_date_time",
        ),
        migrations.AddField(
            model_name="match",
            name="match_date",
            field=models.DateField(
                default=datetime.date(2025, 2, 27),
                help_text="The date when the match occurred",
            ),
            preserve_default=False,
        ),
    ]
