# Generated by Django 4.2.19 on 2025-03-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_hero_played_nullable"),
    ]

    operations = [
        # In SQLite, we need to create new tables and copy the data to remove columns
        migrations.RunSQL(
            sql='''
            -- Create a new PlayerMatchStat table without the hero_played text field
            CREATE TABLE new_api_playermatchstat (
                stats_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                role_played VARCHAR(50) NULL,
                kills INTEGER NOT NULL,
                deaths INTEGER NOT NULL,
                assists INTEGER NOT NULL,
                computed_kda REAL NOT NULL,
                damage_dealt INTEGER NULL,
                damage_taken INTEGER NULL,
                turret_damage INTEGER NULL,
                teamfight_participation REAL NULL,
                gold_earned INTEGER NULL,
                player_notes TEXT NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                match_id INTEGER NOT NULL REFERENCES api_match (match_id),
                player_id INTEGER NOT NULL REFERENCES api_player (player_id),
                team_id INTEGER NOT NULL REFERENCES api_team (team_id),
                hero_played_id INTEGER NULL REFERENCES api_hero (id)
            );
            
            -- Copy data (excluding the hero_played text column)
            INSERT INTO new_api_playermatchstat (
                stats_id, role_played, kills, deaths, assists, computed_kda, 
                damage_dealt, damage_taken, turret_damage, teamfight_participation,
                gold_earned, player_notes, created_at, updated_at, match_id, player_id, team_id, hero_played_id
            )
            SELECT 
                stats_id, role_played, kills, deaths, assists, computed_kda, 
                damage_dealt, damage_taken, turret_damage, teamfight_participation,
                gold_earned, player_notes, created_at, updated_at, match_id, player_id, team_id, hero_played_id
            FROM api_playermatchstat;
            
            -- Drop the old table
            DROP TABLE api_playermatchstat;
            
            -- Rename the new table
            ALTER TABLE new_api_playermatchstat RENAME TO api_playermatchstat;
            
            -- Recreate indexes
            CREATE INDEX api_playermatchstat_match_id_a577e7ab ON api_playermatchstat (match_id);
            CREATE INDEX api_playermatchstat_player_id_47334243 ON api_playermatchstat (player_id);
            CREATE INDEX api_playermatchstat_team_id_13d6ad6f ON api_playermatchstat (team_id);
            CREATE INDEX api_playermatchstat_hero_played_id_f639a82b ON api_playermatchstat (hero_played_id);
            
            -- Create a new DraftInfo table without the hero text field
            CREATE TABLE new_api_draftinfo (
                id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                choice_type VARCHAR(4) NOT NULL,
                draft_position INTEGER NOT NULL,
                draft_phase INTEGER NOT NULL,
                ban_phase VARCHAR(15) NOT NULL,
                draft_format VARCHAR(10) NOT NULL,
                role_picked_for VARCHAR(50) NULL,
                strategy_notes TEXT NULL,
                team_side VARCHAR(4) NOT NULL,
                match_id INTEGER NOT NULL REFERENCES api_match (match_id),
                player_id INTEGER NULL REFERENCES api_player (player_id),
                team_id INTEGER NOT NULL REFERENCES api_team (team_id),
                hero_id INTEGER NULL REFERENCES api_hero (id)
            );
            
            -- Copy data (excluding the hero text column)
            INSERT INTO new_api_draftinfo (
                id, choice_type, draft_position, draft_phase, ban_phase,
                draft_format, role_picked_for, strategy_notes, team_side,
                match_id, player_id, team_id, hero_id
            )
            SELECT 
                id, choice_type, draft_position, draft_phase, ban_phase,
                draft_format, role_picked_for, strategy_notes, team_side,
                match_id, player_id, team_id, hero_id
            FROM api_draftinfo;
            
            -- Drop the old table
            DROP TABLE api_draftinfo;
            
            -- Rename the new table
            ALTER TABLE new_api_draftinfo RENAME TO api_draftinfo;
            
            -- Recreate indexes
            CREATE UNIQUE INDEX api_draftinfo_match_id_draft_position_50d41298_uniq ON api_draftinfo (match_id, draft_position);
            CREATE INDEX api_draftinfo_hero_id_baf1bd12 ON api_draftinfo (hero_id);
            CREATE INDEX api_draftinfo_match_id_68bade84 ON api_draftinfo (match_id);
            CREATE INDEX api_draftinfo_player_id_7b278cd5 ON api_draftinfo (player_id);
            CREATE INDEX api_draftinfo_team_id_4c08e018 ON api_draftinfo (team_id);
            CREATE INDEX api_draftin_team_id_369373_idx ON api_draftinfo (team_id, choice_type, hero_id);
            CREATE INDEX api_draftin_match_i_28e8ef_idx ON api_draftinfo (match_id, team_side);
            CREATE INDEX api_draftin_draft_p_c67b72_idx ON api_draftinfo (draft_position, draft_phase);
            ''',
            reverse_sql='''
            -- No reverse SQL - this operation cannot be undone
            '''
        ),
    ]
