# Generated by Django 4.2.19 on 2025-02-27 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_hero"),
    ]

    operations = [
        migrations.AddField(
            model_name="playermatchstat",
            name="hero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_stats",
                to="api.hero",
            ),
        ),
        migrations.AlterField(
            model_name="playermatchstat",
            name="hero_played",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="playermatchstat",
            name="role_played",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
