# Generated by Django 4.2.19 on 2025-03-02 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_playermatchstat_hero_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "award_type",
                    models.CharField(
                        choices=[
                            ("MVP", "Most Valuable Player"),
                            ("MVP_LOSS", "Most Valuable Player (Losing Team)"),
                            ("MOST_DAMAGE", "Highest Damage"),
                            ("MOST_GOLD", "Highest Gold"),
                            ("MOST_TURRET_DAMAGE", "Most Turret Damage"),
                            ("MOST_DAMAGE_TAKEN", "Most Damage Taken"),
                            ("BEST_KDA", "Best KDA Ratio"),
                            ("MOST_KILLS", "Most Kills"),
                            ("MOST_ASSISTS", "Most Assists"),
                            ("LEAST_DEATHS", "Least Deaths"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stat_value",
                    models.FloatField(
                        blank=True,
                        help_text="The relevant stat value (e.g., KDA for MVP)",
                        null=True,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="api.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="api.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("match", "award_type")},
            },
        ),
    ]
