# Generated by Django 4.2.19 on 2025-03-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_player_role_stats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playermatchstat",
            name="hero",
        ),
    ]
