# Generated by Django 4.2.19 on 2025-04-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_unused_stats_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playermatchstat",
            name="hero_played",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="teammanagerrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("head_coach", "Head Coach"),
                    ("assistant", "Assistant Coach"),
                    ("analyst", "Analyst"),
                    ("viewer", "Viewer"),
                ],
                max_length=20,
            ),
        ),
    ]
