# Generated by Django 4.2.19 on 2025-04-05 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_fix_hero_played_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playermatchstat",
            name="hero_played",
            field=models.ForeignKey(
                blank=True,
                help_text="The hero played by the player in this match",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hero_player_stats",
                to="api.hero",
            ),
        ),
    ]
