# Generated by Django 4.2.19 on 2025-04-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_convert_hero_played_to_foreignkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="mvp",
            field=models.ForeignKey(
                blank=True,
                help_text="Most Valuable Player for this match",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mvp_matches",
                to="api.player",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="mvp_loss",
            field=models.ForeignKey(
                blank=True,
                help_text="Most Valuable Player from the losing team (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mvp_loss_matches",
                to="api.player",
            ),
        ),
        migrations.AlterField(
            model_name="playermatchstat",
            name="computed_kda",
            field=models.FloatField(help_text="KDA value from the game"),
        ),
    ]
