# Generated by Django 4.2.19 on 2025-04-06 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_match_banned_heroes_match_draft_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="banned_heroes",
        ),
        migrations.RemoveField(
            model_name="match",
            name="draft_notes",
        ),
        migrations.RemoveField(
            model_name="playermatchstat",
            name="draft_pick_order",
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("6_BANS", "6 Bans (3 per team)"),
                            ("10_BANS", "10 Bans (5 per team)"),
                        ],
                        default="6_BANS",
                        max_length=20,
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the draft has been fully completed",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Draft strategy notes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft",
                        to="api.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DraftPick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_side",
                    models.CharField(
                        choices=[("BLUE", "Blue Side"), ("RED", "Red Side")],
                        max_length=10,
                    ),
                ),
                (
                    "pick_order",
                    models.IntegerField(help_text="Order in which pick occurred (1-5)"),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picks",
                        to="api.draft",
                    ),
                ),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_picks",
                        to="api.hero",
                    ),
                ),
            ],
            options={
                "ordering": ["team_side", "pick_order"],
                "unique_together": {("draft", "team_side", "pick_order")},
            },
        ),
        migrations.CreateModel(
            name="DraftBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_side",
                    models.CharField(
                        choices=[("BLUE", "Blue Side"), ("RED", "Red Side")],
                        max_length=10,
                    ),
                ),
                (
                    "ban_order",
                    models.IntegerField(help_text="Order in which ban occurred (1-5)"),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bans",
                        to="api.draft",
                    ),
                ),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_bans",
                        to="api.hero",
                    ),
                ),
            ],
            options={
                "ordering": ["team_side", "ban_order"],
                "unique_together": {("draft", "team_side", "ban_order")},
            },
        ),
    ]
