# Generated by Django 4.2.19 on 2025-04-16 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_match_match_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="winning_team",
            field=models.ForeignKey(
                blank=True,
                help_text="The team that won the match (used for both internal and external matches)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_matches",
                to="api.team",
            ),
        ),
    ]
