# Generated by Django 4.2.19 on 2025-04-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_match_winning_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="blue_side_team",
            field=models.ForeignKey(
                blank=True,
                help_text="The team playing on the blue side (only for external matches)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blue_side_matches",
                to="api.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="red_side_team",
            field=models.ForeignKey(
                blank=True,
                help_text="The team playing on the red side (only for external matches)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="red_side_matches",
                to="api.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="match_outcome",
            field=models.CharField(
                blank=True,
                choices=[("VICTORY", "Victory"), ("DEFEAT", "Defeat")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="opponent_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opponent_matches",
                to="api.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="our_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="our_team_matches",
                to="api.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="scrim_type",
            field=models.CharField(
                choices=[
                    ("SCRIMMAGE", "Scrimmage"),
                    ("TOURNAMENT", "Tournament"),
                    ("RANKED", "Ranked"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team_side",
            field=models.CharField(
                blank=True,
                choices=[("BLUE", "Blue Side"), ("RED", "Red Side")],
                max_length=10,
                null=True,
            ),
        ),
    ]
