# Generated by Django 4.2.19 on 2025-04-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_populate_sides"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="is_external_match",
        ),
        migrations.RemoveField(
            model_name="match",
            name="opponent_team",
        ),
        migrations.RemoveField(
            model_name="match",
            name="team_side",
        ),
        migrations.AlterField(
            model_name="match",
            name="blue_side_team",
            field=models.ForeignKey(
                help_text="The team playing on the blue side",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blue_side_matches",
                to="api.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="our_team",
            field=models.ForeignKey(
                blank=True,
                help_text="The participating team managed by the user submitting the data (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="our_perspective_matches",
                to="api.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="red_side_team",
            field=models.ForeignKey(
                help_text="The team playing on the red side",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="red_side_matches",
                to="api.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="winning_team",
            field=models.ForeignKey(
                blank=True,
                help_text="The team that won the match",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_matches",
                to="api.team",
            ),
        ),
    ]
