# Generated by Django 4.2.19 on 2025-04-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_remove_match_is_external_match_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playermatchstat",
            name="computed_kda",
        ),
        migrations.AddField(
            model_name="playermatchstat",
            name="kda",
            field=models.FloatField(
                blank=True,
                help_text="KDA ratio provided by the game (user input)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="playermatchstat",
            name="medal",
            field=models.CharField(
                blank=True,
                choices=[("GOLD", "Gold"), ("SILVER", "Silver"), ("BRONZE", "Bronze")],
                help_text="Medal awarded for performance (Gold, Silver, Bronze)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="playerteamhistory",
            name="is_starter",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the player is part of the main starting lineup for this team during this period",
            ),
        ),
    ]
