# Generated by Django 5.1.5 on 2025-04-16 12:07

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_playermatchstat_computed_kda_and_more'),
    ]

    operations = [
        # Make the fields nullable temporarily to allow for data migration in the next step
        migrations.AlterField(
            model_name='match',
            name='blue_side_team',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='blue_side_matches',
                to='api.team',
                help_text="The team playing on the blue side"
            ),
        ),
        migrations.AlterField(
            model_name='match',
            name='red_side_team',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='red_side_matches',
                to='api.team',
                help_text="The team playing on the red side"
            ),
        ),
    ] 