# Generated by Django 5.1.5 on 2025-04-16 12:09

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_populate_sides'),
    ]

    operations = [
        # Make the fields non-nullable again after data has been migrated
        migrations.AlterField(
            model_name='match',
            name='blue_side_team',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='blue_side_matches',
                to='api.team',
                help_text="The team playing on the blue side"
            ),
        ),
        migrations.AlterField(
            model_name='match',
            name='red_side_team',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='red_side_matches',
                to='api.team',
                help_text="The team playing on the red side"
            ),
        ),
    ] 