# Generated by Django 4.2.19 on 2025-04-21 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0027_make_sides_non_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchEditHistory",
            fields=[
                ("edit_id", models.AutoField(primary_key=True, serialize=False)),
                ("edit_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "edit_type",
                    models.CharField(
                        choices=[
                            ("MATCH_METADATA", "Match Metadata"),
                            ("PLAYER_STATS", "Player Statistics"),
                            ("TEAMS", "Team Assignments"),
                            ("OUTCOME", "Match Outcome"),
                            ("NOTES", "Match Notes"),
                        ],
                        max_length=20,
                    ),
                ),
                ("previous_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("edit_reason", models.TextField(blank=True, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_history",
                        to="api.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-edit_timestamp"],
            },
        ),
    ]
