# Generated by Django 4.2.19 on 2025-04-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_matchedithistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matchedithistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Match edit histories",
            },
        ),
        migrations.RenameField(
            model_name="matchedithistory",
            old_name="edit_timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="matchedithistory",
            old_name="user",
            new_name="edited_by",
        ),
        migrations.AddField(
            model_name="matchedithistory",
            name="related_player_stat_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID of the related player stat for player stat edits",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="matchedithistory",
            name="edit_type",
            field=models.CharField(
                choices=[
                    ("MATCH_METADATA", "Match Metadata Edit"),
                    ("PLAYER_STATS", "Player Statistics Edit"),
                    ("MATCH_RESTORE", "Match Restore"),
                    ("PLAYER_STATS_RESTORE", "Player Statistics Restore"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="matchedithistory",
            name="new_values",
            field=models.TextField(help_text="JSON string of new values"),
        ),
        migrations.AlterField(
            model_name="matchedithistory",
            name="previous_values",
            field=models.TextField(help_text="JSON string of previous values"),
        ),
    ]
