# Generated by Django 4.2.19 on 2025-02-27 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_match_match_date_time_match_match_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="is_external_match",
            field=models.BooleanField(
                default=False,
                help_text="Whether this match is between external teams (not involving our team)",
                verbose_name="External Match",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="scrim_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="api.scrimgroup",
            ),
        ),
    ]
