# Generated by Django 4.2.19 on 2025-02-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_match_is_external_match_alter_match_scrim_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("role", models.CharField(blank=True, max_length=50)),
                ("released_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
