# Generated by Django 4.2.19 on 2025-03-02 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_matchaward"),
    ]

    operations = []
