# Generated by Django 4.2.19 on 2025-03-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_player_role_stats"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playerrolestats",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="playerrolestats",
            name="player",
        ),
        migrations.AlterField(
            model_name="teammanagerrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("MANAGER", "Team Manager"),
                    ("COACH", "Coach"),
                    ("ANALYST", "Analyst"),
                    ("ADMIN", "Administrator"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="HeroPairingStats",
        ),
        migrations.DeleteModel(
            name="PlayerRoleStats",
        ),
    ]
