# Generated by Django 4.2.19 on 2025-03-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_unused_stats_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammanagerrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("head_coach", "Head Coach"),
                    ("assistant", "Assistant Coach"),
                    ("analyst", "Analyst"),
                    ("viewer", "Viewer"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DraftInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_type",
                    models.CharField(
                        choices=[("PICK", "Pick"), ("BAN", "Ban")], max_length=4
                    ),
                ),
                ("hero", models.CharField(max_length=100)),
                ("draft_position", models.IntegerField()),
                (
                    "draft_phase",
                    models.IntegerField(
                        choices=[
                            (1, "First Phase"),
                            (2, "Second Phase"),
                            (3, "Third Phase"),
                        ]
                    ),
                ),
                (
                    "ban_phase",
                    models.CharField(
                        choices=[
                            ("FIRST_ROUND", "First Ban Round (2+2)"),
                            ("SECOND_ROUND", "Second Ban Round (1+1)"),
                            ("THIRD_ROUND", "Third Ban Round (1+1)"),
                            ("NONE", "Not a Ban"),
                        ],
                        default="NONE",
                        help_text="Specific ban round in the draft process",
                        max_length=15,
                    ),
                ),
                (
                    "draft_format",
                    models.CharField(
                        choices=[
                            ("6BAN", "6-Ban Format (2-2-1-1)"),
                            ("10BAN", "10-Ban Format (2-2-1-1-1-1-1-1)"),
                            ("CUSTOM", "Custom Format"),
                        ],
                        default="6BAN",
                        help_text="Ban format used in this match",
                        max_length=10,
                    ),
                ),
                (
                    "role_picked_for",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "strategy_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes on why this hero was picked/banned",
                        null=True,
                    ),
                ),
                (
                    "team_side",
                    models.CharField(
                        choices=[
                            ("BLUE", "Blue Side (First Pick)"),
                            ("RED", "Red Side (Second Pick)"),
                        ],
                        help_text="Whether team was blue (first pick) or red side",
                        max_length=4,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_info",
                        to="api.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_choices",
                        to="api.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_records",
                        to="api.team",
                    ),
                ),
            ],
            options={
                "ordering": ["match", "draft_position"],
                "indexes": [
                    models.Index(
                        fields=["team", "choice_type", "hero"],
                        name="api_draftin_team_id_fc828d_idx",
                    ),
                    models.Index(
                        fields=["match", "team_side"],
                        name="api_draftin_match_i_28e8ef_idx",
                    ),
                    models.Index(
                        fields=["draft_position", "draft_phase"],
                        name="api_draftin_draft_p_c67b72_idx",
                    ),
                ],
                "unique_together": {("match", "draft_position")},
            },
        ),
    ]
